"""Compare two query-set runs (nano baseline vs qdrant) question by question.

The behavioural bar agreed for this migration: substantively the same answers,
citing the same sources. Wording will differ -- the answer is regenerated by an
LLM -- so this does NOT diff prose. It compares the two things that are
actually determined by the vector store:

  retrieval  - the set of entities the context was built from
  sources    - the files cited in the answer's References section

    python compare_querysets.py queryset_nano.json queryset_qdrant.json
"""
import json
import io
import os
import re
import sys

ENTITY_RE = re.compile(r'"entity":\s*"((?:[^"\\]|\\.)*)"')
FILE_RE = re.compile(r'[\w\-.,()]+\.(?:pdf|md)', re.IGNORECASE)


def entities(context):
    return {m.group(1) for m in ENTITY_RE.finditer(context or "")}


def refs(answer):
    """Files listed under the answer's References heading."""
    if not answer:
        return set()
    tail = answer.split("### References", 1)
    if len(tail) < 2:
        return set(FILE_RE.findall(answer))
    return set(FILE_RE.findall(tail[1]))


def jaccard(a, b):
    if not a and not b:
        return 1.0
    return len(a & b) / len(a | b) if (a | b) else 1.0


def overlap(a, b):
    """Fraction of the baseline's items that the new run also found."""
    return len(a & b) / len(a) if a else 1.0


def main():
    p_a, p_b = sys.argv[1], sys.argv[2]
    A = json.load(io.open(p_a, encoding="utf-8"))
    B = json.load(io.open(p_b, encoding="utf-8"))
    ra = {r["n"]: r for r in A["results"]}
    rb = {r["n"]: r for r in B["results"]}

    print("A = {} ({} results)".format(os.path.basename(p_a), len(ra)))
    print("B = {} ({} results)\n".format(os.path.basename(p_b), len(rb)))
    print("  #   ent_A  ent_B  keep   jacc   refs_A refs_B  same_refs   ms_A    ms_B")
    print("  " + "-" * 74)

    keeps, jaccs, ref_same, ctx_a, ctx_b, ans_a, ans_b = [], [], [], [], [], [], []
    for n in sorted(ra):
        a, b = ra[n], rb.get(n)
        if b is None:
            print("  {:<3} MISSING in B".format(n))
            continue
        ea, eb = entities(a["context"]), entities(b["context"])
        fa, fb = refs(a["answer"]), refs(b["answer"])
        k, j = overlap(ea, eb), jaccard(ea, eb)
        same = "yes" if fa == fb else "{}/{}".format(len(fa & fb), len(fa | fb))
        keeps.append(k)
        jaccs.append(j)
        ref_same.append(fa == fb)
        ctx_a.append(a["context_ms"])
        ctx_b.append(b["context_ms"])
        ans_a.append(a["answer_ms"])
        ans_b.append(b["answer_ms"])
        print("  {:<3} {:>6} {:>6}  {:>5.0%} {:>6.2f}  {:>6} {:>6}  {:>9}  {:>6} {:>7}".format(
            n, len(ea), len(eb), k, j, len(fa), len(fb), same,
            a["context_ms"], b["context_ms"]))

    def med(v):
        return sorted(v)[len(v) // 2]

    print("\n  retrieval kept (mean)   {:.1%}".format(sum(keeps) / len(keeps)))
    print("  jaccard       (mean)   {:.3f}".format(sum(jaccs) / len(jaccs)))
    print("  identical reference sets {}/{}".format(sum(ref_same), len(ref_same)))
    print("\n  context ms   median  A={:>6}  B={:>6}".format(med(ctx_a), med(ctx_b)))
    print("  answer  ms   median  A={:>6}  B={:>6}".format(med(ans_a), med(ans_b)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
